spring.application.name=demo

spring.ai.openai.api-key=${OPENAI_API_KEY}
logging.level.org.springframework.ai.chat.client.advisor=DEBUG


spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}


spring.security.oauth2.client.registration.google.scope[0]=openid
spring.security.oauth2.client.registration.google.scope[1]=profile
spring.security.oauth2.client.registration.google.scope[2]=email
spring.security.oauth2.client.registration.google.scope[3]=https://www.googleapis.com/auth/calendar